Added Migration, modified the front page, SLURM
arcs-njit-edu/Docs pull request #21
Opened 2023-12-13 17:49 UTC by absrocks

2023-12-13 18:38 UTC, alexpacheco commented on docs/facilities/hpc-course.md
This feels very out of place within the facilities directory. The first half reads like a policy or request form that we require while the second half would fall more under education and training resources or instructional support for incorporating HPC in courses.

2023-12-13 18:41 UTC, alexpacheco commented on docs/stylesheets/extra.css
The svg file should be stored locally. If someone changes the file maliciously, then we would be displaying an incorrect logo. Also, we should use a logo provided by Start Comm, this is an official NJIT webpage

2023-12-13 18:43 UTC, alexpacheco commented on mkdocs.yml
See my previous comment on the HPC course page. Creating a directory for Training/Instruction/Education/{something more appropriate} and adding hpc-course.md to that directory would be logical

2023-12-13 18:50 UTC, alexpacheco commented on docs/Software/programming/python/conda.md
Considering the number of issues that we see due to pip installation, it would be wise to put up a big alert block advising users to not use pip or to not mix pip and conda, both here and in the main python page

2023-12-13 18:56 UTC, alexpacheco commented on docs/Software/slurm/slurm.md
Line 32 should be sbatch [submit script].

You can add
Run a command: `srun <slurm options> <command name>`

In the table following, put Interactive login after Job submission

2023-12-13 18:57 UTC, alexpacheco commented on docs/Software/slurm/slurm.md
Should consider putting quota_info ab1234 in profile.d so that usage information is printed when users login

2023-12-14 03:17 UTC, absrocks commented on docs/facilities/hpc-course.md
I have created "services" section and moved the file there. We can add several segments such as HPC training, and presentations under this section. let me know if you prefer another name for the section.

2023-12-14 03:18 UTC, absrocks commented on docs/stylesheets/extra.css
I have removed the link and used the same logo which is used at the left corner of the website.

2023-12-14 03:19 UTC, absrocks commented on docs/Software/programming/python/conda.md
Added the warning section

2023-12-14 03:21 UTC, absrocks commented on docs/Software/slurm/slurm.md
Modified line 32.
about quota_info, I know that we should include this in profile.d, but for now, I just added it to provide the information, in case user want to check their quota, I will remove it once XISS implements this change.

2023-12-14 10:14 UTC, alexpacheco commented on docs/Software/slurm/slurm.md
That's what I implied, have XISS implement it in profile.d so that most users do not need to remember the command

2024-01-22 17:39 UTC, gwolosh requested changes
I would remove line 39. This is an inomplete command which will error if entered as is. There are more complete instructions further on in. the page.

2024-04-01 00:06 UTC, closed without merging