Modified migration FAQ, front page, SLURM, Conda
arcs-njit-edu/Docs pull request #26
Opened 2024-01-26 02:44 UTC by absrocks

Created a fresh PR that has fewer file changes.

2024-01-26 02:46 UTC, absrocks commented
Check the preview at https://absrocks.github.io/Docs/

2024-01-26 11:18 UTC, alexpacheco commented on docs/clusters/index.md
Wulver should be listed as current cluster.

2024-01-26 11:19 UTC, alexpacheco commented on docs/clusters/wulver.md
Wulver is NJIT's newest High Performance Cluster made available to user in Jan 2024.

2024-01-26 11:21 UTC, alexpacheco commented on docs/Policies/wulver_policies.md
> +    * Wall time: 72 hours (default), PI can request longer walltimes up to 30 days. ARCS HPC reserves the right to reboot nodes once a month for maintenance — the second Tuesday of each month. See [C
Check the link to the maintenance page

2024-01-26 11:22 UTC, alexpacheco commented
Make the front page blocks, HPC Highlights and HPC News horizontal so that it is easier to read

2024-01-26 13:31 UTC, alexpacheco commented on docs/news/posts/2024-01-22.md
@gwolosh @khill42 How does this wording sound?

Beginning Feb 1, 2024, ARCS HPC will be instituting a monthly maintenance downtime on all HPC systems on the second Tuesday from 9AM - 9PM. Wulver and the associated GPFS storage will be taken out of service for maintenance, repairs, patches and upgrades. During the maintenance downtime, logins will be disabled, users will not have access to their stored data in /project, /home and /scratch. All jobs that do not end before 9AM will held by the scheduler until the downtime is complete and the systems are returned to service. 

(example)

We anticipate maintenance to be completed by the scheduled time. However, occasionally the maintenance may be completed earlier than scheduled or could be extended to the following days. A notification will be sent to the user mailing list when the systems are returned to service or the maintenance window is extended. Users should take into account the maintenance window when scheduling jobs and developing plans to meet various deadlines. Please do not contact the help desk, HPC staff or open SNOW tickets for access to the cluster or data during the maintenance downtime. All such requests via email will be ignored and SNOW tickets closed as resolved with no responses.

2024-01-29 16:22 UTC, absrocks commented on docs/clusters/wulver.md
Corrected

2024-01-29 16:22 UTC, absrocks commented on docs/clusters/index.md
Corrected

2024-01-29 16:23 UTC, absrocks commented on docs/Policies/wulver_policies.md
> +    * Wall time: 72 hours (default), PI can request longer walltimes up to 30 days. ARCS HPC reserves the right to reboot nodes once a month for maintenance — the second Tuesday of each month. See [C
Fixed the link

2024-01-30 15:14 UTC, khill42 commented on docs/Software/slurm/slurm.md
>  Group quotas for xy1234
The output of this script has changed significantly, please update output here

2024-01-30 15:20 UTC, khill42 commented on docs/assets/tables/facilities.csv
> +InfiniBand,"mix of HDR100, EDR, and FDR",HDR100 and 10Gig
Network (Infiniband; Ethernet) "mix of HDR100, EDR, and FDR",HDR100; 10Gig

2024-01-30 15:32 UTC, khill42 commented on docs/clusters/Wulver_filesystems.md
> +1. The `$HOME` directory is not intended for primary storage and will have only 50GB quota. To run the simulations, compilations, etc., users need to use a project directory which has 2TB of storage
The `$HOME` directory is not intended for primary storage and has a 50GB quota. The main location for storing files is the group project directory which has 2TB of storage per PI group.

2024-01-30 15:34 UTC, khill42 commented on docs/clusters/wulver.md
> +Wulver is a new cluster anticipated to be available at the end of 2023. To get started with Wulver, please check the details in [get started on Wulver](get_started_on_Wulver.md)
Wulver is NJIT's newest cluster which went into production in early 2024.

2024-01-30 15:36 UTC, khill42 commented on docs/migration/faqs.md
> +          - If you code is compiled based on [FOSS Toolchain](compilers.md#free-open-source-software-(foss)) (GCC and OpenMPI), you need to compile the code the samw way you did in Lochness. Just mak
If your code is compiled based on [FOSS Toolchain](compilers.md#free-open-source-software-(foss)) (GCC and OpenMPI), you need to compile the code the same way you did in Lochness.

2024-01-30 15:36 UTC, khill42 commented on docs/migration/faqs.md
> +          - If your code is based on the [Intel toolchain](compilers.md#intel), you need to add the follwoing while configuring your code.
following

2024-01-30 15:37 UTC, khill42 commented on docs/migration/faqs.md
> +          - When installing codes, ensure that you perform the installation on the compute node rather than the login node. Since the hardware architecture is different on the login node, it's best p
You need to initiate an [interactive session with compute node]

2024-01-30 15:38 UTC, khill42 commented on docs/migration/faqs.md
>        In addition to documentation, the research facilitation team is committed to providing personal assistance to faculty and researchers. If you have specific questions, require hands-on support,
We are here to ensure that you receive the assistance you need for a successful transition.

2024-01-30 15:39 UTC, khill42 requested changes
reviewed everything, there's a few minor corrections.

2024-01-30 15:46 UTC, khill42 commented on docs/news/posts/2024-01-22.md
We could include a reminder to read the motd each time you login for cluster service information:
Look for the Message of the Day when you log in to remind you of upcoming downtimes or other important cluster information.

2024-02-06 16:17 UTC, khill42 commented
I approved the changes but it still says review required and the merge is blocked.

2024-02-06 16:37 UTC, gwolosh approved these changes

2024-02-06 16:40 UTC, merged